# Generated by Django 4.2.5 on 2023-12-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectmanager_project_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='check1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
