# Generated by Django 4.2.5 on 2023-12-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_check1'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='check2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
