# Generated by Django 4.2.5 on 2024-01-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
